name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 25.x, 26.x]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install packages
        run: |
          pnpm install

      - name: Build package
        working-directory: ./packages/react-responsive
        run: |
          pnpm build

      - name: Run tests
        run: |
          pnpm exec playwright install --with-deps chromium
          pnpm test

      - name: Check linting
        run: |
          pnpm lint

      - name: Typecheck
        run: |
          pnpm typecheck
